### ISSUE TITLE
NPE in Kotlin branch

### ISSUE THREAD

**Issue by tangjingyuan** [kinfoundation/kin-ecosystem-android-sdk#249]
If you click the Transaction History when the spend offers is not loaded, it will occurs KotlinNullPointerException.

See the log below:

kotlin.KotlinNullPointerException
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.marketplace.presenter.MarketplacePresenter.syncOffers(MarketplacePresenter.kt:235)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.marketplace.presenter.MarketplacePresenter.access$syncOffers(MarketplacePresenter.kt:32)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.marketplace.presenter.MarketplacePresenter$getOffers$1.onResponse(MarketplacePresenter.kt:205)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.marketplace.presenter.MarketplacePresenter$getOffers$1.onResponse(MarketplacePresenter.kt:202)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.core.data.offer.OfferRepository$2.onResponse(OfferRepository.java:78)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.core.data.offer.OfferRepository$2.onResponse(OfferRepository.java:73)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.kin.ecosystem.core.data.offer.OfferRemoteData$1$2.run(OfferRemoteData.java:57)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;android.os.Handler.handleCallback(Handler.java:739)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;android.os.Handler.dispatchMessage(Handler.java:95)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;android.os.Looper.loop(Looper.java:135)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;android.app.ActivityThread.main(ActivityThread.java:5254)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.lang.reflect.Method.invoke(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;java.lang.reflect.Method.invoke(Method.java:372)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
&nbsp;&nbsp;&nbsp;&nbsp;at&nbsp;com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by OrenZak** [comment]
Thanks for your feedback @tangjingyuan, it was fixed with the latest commit on the same branch.
