### ISSUE TITLE
kotlin.UninitializedPropertyAccessException in OnboardingFragment

### ISSUE THREAD

**Issue by tangjingyuan** [kinfoundation/kin-ecosystem-android-sdk#303]
Hi @OrenZak , we watched a kotlin exception occurred in OnboardingFragment. SDK version is 1.0.1. Here is the crash log:

![image](https://user-images.githubusercontent.com/12523498/56780523-38040b80-6812-11e9-8216-72df58199373.png)

**Comment by OrenZak** [comment]
Hi @tangjingyuan thank you for letting me know, I will investigate it.
