### ISSUE TITLE
NullPointerException in EcosystemActivity

### ISSUE THREAD

**Issue by tangjingyuan** [kinfoundation/kin-ecosystem-android-sdk#304]
Hi @OrenZak , a NPE occurred in EcosystemActivity. The SDK version is 1.0.1. Here is the crash log:
![image](https://user-images.githubusercontent.com/12523498/56780570-5ec24200-6812-11e9-94ef-1862ce1082f8.png)

**Comment by OrenZak** [comment]
Hi @tangjingyuan thank you for letting me know, I will investigate it.
