### ISSUE TITLE
Question about the getUserLoginState, setJWT and logout methods

### ISSUE THREAD

**Issue by tangjingyuan** [kinfoundation/kin-ecosystem-android-sdk#310]
Hi @OrenZak , I have a question about the getUserLoginState, setJWT and logout methods

In Kin.login(JWT) method, you use AuthRepository.getInstance().getUserLoginState(JWT) to check the loginState. If the input user_id or device_id in jwt are different with the cached data, the logout method will be invoked. 

But the cached data will not be clear if Kin SDK is not logged in before because the result of isAccountLoggedIn.compareAndSet(true, false) is false in logout method.

For example, user use user_id_1 to get jwt_1 and auth_token_1 and login Kin Successfully, then he logout app without call Kin#logout(developers forget to call Kin.logout when logout app's account) and kill app. In next time he use user_id_2 to try to login, but SDK will use user_id_1's authToken to try log in because user_id_1's authToken is not expired.

**Comment by tangjingyuan** [comment]
I use the following codes to make sure the cached data is cleared when intialize and log in Kin if current user_id is different with cached data:
![image](https://user-images.githubusercontent.com/12523498/57669823-3a9e9780-763f-11e9-8b3e-2519d6f34425.png)

But I cannot access the AuthRepository, BlockchainSourceImpl, AccountManagerImpl, OrderRepository and OfferRepository after upgrade gradle. So I submit the issue.

BTW, I think it's better to call setJWT after login successfully.

**Comment by OrenZak** [comment]
Hi @tangjingyuan , thanks for letting me know about this.
The first thought was if a user switch accounts so we will log him out from the current account.
Regarding the issue you raised, I will find a solution and update ASAP, meantime if you know your user did logout please call `Kin.logout(...)`.
Moreover, you should not use any internal objects as you can change internal states and may cause issues.
